### ISSUE TITLE
Intended behavior when clicking map points?

### ISSUE THREAD

**Issue by cjdd3b** [striblab/super-bowl-guide#13]
From the map view, clicking on a point other than the highlighted one currently does this, which seems kind of like an afterthought:

![screen shot 2018-01-16 at 10 23 31 am](https://user-images.githubusercontent.com/947791/34999435-4793db2c-faa7-11e7-9e13-ed60a1e91a65.png)

What would you think about either:

  - Clicking on a point highlights it (turns it purple) and then scrolls the left rail to the corresponding item.
  - Just not showing the un-highlighted points

**Comment by zzolo** [comment]
Good suggestion
