### ISSUE TITLE
Telephone protocol on desktop

### ISSUE THREAD

**Issue by cjdd3b** [striblab/super-bowl-guide#4]
The tel: links don't really do anything on desktop views, even though they are still clickable. Worth doing any responsive css/JS voodoo to downplay their clickiness at larger viewports?

**Comment by zzolo** [comment]
To note, there is no way to say with JS or CSS "on a phone".  The best one can do is either touch or screen size.  It makes most sense to do screen size.

**Comment by cjdd3b** [comment]
Or there are also preposterous [mobile browser detection regexes](https://stackoverflow.com/questions/11381673/detecting-a-mobile-browser). Though I'd call this low priority either way.
