### ISSUE TITLE
Clicking on a map point zooms out the map

### ISSUE THREAD

**Issue by cjdd3b** [striblab/super-bowl-guide#41]
Not sure if this is related to #39. Easier to explain how to replicate than to try and describe it in words:

  - Go [here](https://static.startribune.com/news/projects-staging/all/super-bowl-guide/lists/moa_food.html)
  - Click the Map link at the top
  - Click one of the greyed out points

When I do that, the map zooms way out — though the point is highlighted and the left rail is scrolled properly.

**Comment by zzolo** [comment]
Maybe this is an issue with the fitBounds.  So, if it got your location, it will try to zoom to that item and your location (the little person marker).  But, maybe you don't see it given the zoom level and all that.

**Comment by zzolo** [comment]
I think this is the intended behavior, just kind of odd given for this specific content where all the points are so close together.

Will make another issue for handling location when way outside the Twin Cities
