### ISSUE TITLE
Scroll behavior not changing/highlighting entries on Firefox or Safari

### ISSUE THREAD

**Issue by cjdd3b** [striblab/super-bowl-guide#7]
Nothing seems to happen when I scroll down [this page](https://static.startribune.com/news/projects-staging/all/super-bowl-guide/lists/10_burgers.html) on FF and Safari, though it does work on Chrome. Haven't checked IE, but worth doing.

Using FF 45.0, Safari 11.0.1 on Mac

**Comment by zzolo** [comment]
Works on FF 58.0b14 (Developer Edition) for me, FYI.

**Comment by cjdd3b** [comment]
Weird. Decent chance this is a red herring, but I do get this console warning on FF45:

![screen shot 2018-01-16 at 10 36 26 am](https://user-images.githubusercontent.com/947791/35000203-66dc2fd2-faa9-11e7-915f-1baee51909cb.png)

**Comment by cjdd3b** [comment]
Ahh, totally makes sense. Thanks.

**Comment by zzolo** [comment]
Closing in favor of #22
